export const showAtomName = (proton: number): string => {
  switch (proton) {
    case 1:
      return 'Hidrogênio'
    case 2:
      return 'Hélio'
    case 3:
      return 'Lítio'
    case 4:
      return 'Berílio'
    case 5:
      return 'Boro'
    case 6:
      return 'Carbono'
    case 7:
      return 'Nitrogênio'
    case 8:
      return 'Oxigênio'
    case 9:
      return 'Flúor'
    case 10:
      return 'Neônio'
    case 11:
      return 'Sódio'
    case 12:
      return 'Magnésio'
    case 13:
      return 'Alumínio'
    case 14:
      return 'Silício'
    case 15:
      return 'Fósforo'
    case 16:
      return 'Enxofre'
    case 17:
      return 'Cloro'
    case 18:
      return 'Argônio'
    case 19:
      return 'Potássio'
    case 20:
      return 'Cálcio'
    case 21:
      return 'Escândio'
    case 22:
      return 'Titânio'
    case 23:
      return 'Vanádio'
    case 24:
      return 'Cromo'
    case 25:
      return 'Manganês'
    case 26:
      return 'Ferro'
    case 27:
      return 'Cobalto'
    case 28:
      return 'Níquel'
    case 29:
      return 'Cobre'
    case 30:
      return 'Zinco'
    case 31:
      return 'Gálio'
    case 32:
      return 'Germânio'
    case 33:
      return 'Arsênio'
    case 34:
      return 'Selênio'
    case 35:
      return 'Bromo'
    case 36:
      return 'Criptônio'
    case 37:
      return 'Rubídio'
    case 38:
      return 'Estrôncio'
    case 39:
      return 'Ítrio'
    case 40:
      return 'Zircônio'
    case 41:
      return 'Nióbio'
    case 42:
      return 'Molibdênio'
    case 43:
      return 'Tecnécio'
    case 44:
      return 'Rutênio'
    case 45:
      return 'Ródio'
    case 46:
      return 'Paládio'
    case 47:
      return 'Prata'
    case 48:
      return 'Cádmio'
    case 49:
      return 'Índio'
    case 50:
      return 'Estanho'
    case 51:
      return 'Antimônio'
    case 52:
      return 'Telúrio'
    case 53:
      return 'Iodo'
    case 54:
      return 'Xenônio'
    case 55:
      return 'Césio'
    case 56:
      return 'Bário'
    case 57:
      return 'Lantânio'
    case 58:
      return 'Cério'
    case 59:
      return 'Praseodímio'
    case 60:
      return 'Neodímio'
    case 61:
      return 'Promécio'
    case 62:
      return 'Samário'
    case 63:
      return 'Európio'
    case 64:
      return 'Gadolínio'
    case 65:
      return 'Térbio'
    case 66:
      return 'Disprósio'
    case 67:
      return 'Hólmio'
    case 68:
      return 'Érbio'
    case 69:
      return 'Túlio'
    case 70:
      return 'Itérbio'
    case 71:
      return 'Lutécio'
    case 72:
      return 'Háfnio'
    case 73:
      return 'Tântalo'
    case 74:
      return 'Tungstênio'
    case 75:
      return 'Rênio'
    case 76:
      return 'Ósmio'
    case 77:
      return 'Irídio'
    case 78:
      return 'Platina'
    case 79:
      return 'Ouro'
    case 80:
      return 'Mercúrio'
    case 81:
      return 'Tálio'
    case 82:
      return 'Chumbo'
    case 83:
      return 'Bismuto'
    case 84:
      return 'Polônio'
    case 85:
      return 'Astato'
    case 86:
      return 'Radônio'
    case 87:
      return 'Frâncio'
    case 88:
      return 'Rádio'
    case 89:
      return 'Actínio'
    case 90:
      return 'Tório'
    case 91:
      return 'Protactínio'
    case 92:
      return 'Urânio'
    case 93:
      return 'Netúnio'
    case 94:
      return 'Plutônio'
    case 95:
      return 'Amerício'
    case 96:
      return 'Cúrio'
    case 97:
      return 'Bérquelio'
    case 98:
      return 'Califórnio'
    case 99:
      return 'Einsteínio'
    case 100:
      return 'Férmio'
    case 101:
      return 'Mendelévio'
    case 102:
      return 'Nobélio'
    case 103:
      return 'Laurêncio'
    case 104:
      return 'Rutherfórdio'
    case 105:
      return 'Dúbnio'
    case 106:
      return 'Seabórgio'
    case 107:
      return 'Bóhrio'
    case 108:
      return 'Hássio'
    case 109:
      return 'Meitnério'
    case 110:
      return 'Darmstádio'
    case 111:
      return 'Roentgênio'
    case 112:
      return 'Copernício'
    case 113:
      return 'Nihônio'
    case 114:
      return 'Fleróvio'
    case 115:
      return 'Moscóvio'
    case 116:
      return 'Livermório'
    case 117:
      return 'Tenessino'
    case 118:
      return 'Oganessônio'
    default:
      return 'Elemento Desconhecido'
  }
}
